# Site settings
title: Chennan's Note
email: chennancd@gmail.com
description: This is Chennan's Note.
baseurl: "/TechNote" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  chennanni

# Build settings
markdown: kramdown
