# Site settings
title: Chennan's Note
email: chennancd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  my note for sharing
baseurl: "TechNote" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  chennanni

# Build settings
markdown: kramdown
